### ISSUE TITLE
Cancel button needed for edit taxon: 

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#126]
I was testing the new layout and want to request a cancel botton for the edit a taxon feature. Otherwise, if you arrive at this page: http://ec2-52-26-62-57.us-west-2.compute.amazonaws.com/taxa/440989/edit and do not want to make an edit, it is not clear how to cancel the edit.

**Comment by jonkerz** [comment]
Restoring the cancel buttons is very easy, and I can do that right now, but first I want to repeat this from the commit message in case you did not see it (6bb9d43716369e84517ec29cc2ed927ae3bef440):

> Removed taxa/reference cancel links
> They are basically back buttons that give the false impression that cancelling would do anything other that what just leaving the page or closing the browser would. May lead editors to believe that changes/deletions of synonyms/history_items/etc would be rolled back, which is not true.

For example, say an editor edits a taxon and adds synonym, changes the status to valid and updates a bunch of history items. Then they realize that they are on the wrong taxon page, so they click "Cancel". In this case, only the status change would have been canceled (or more precisely, the status change would never had been saved in the first place, as opposed to the synonym and history items, which are saved before hitting the form's main save button).

I know which type of edits are reverted and which are not because I've tested it and figured it out from reading the code, and that's also how I know that closing the browser window or clicking on another link has the same effect. This is not intuitive at all, and I'm pretty sure everyone agrees -- but as long as the cancel buttons don't actually cancel, then I think they confuse more than they make editing easier.

@bpescador Cancel buttons, yay or nay?

**Comment by bpescador** [comment]
@jonkerz Thanks for the clarification on the cancel button, so how about just a link on the top to leave edit mode. There just needs a clear way to return to the previous page instead of the browser back botton which we have all be trained not to use on database sites.

**Comment by jonkerz** [comment]
@bpescador What if we restore the cancel buttons but add a tooltips for them? "Click to leave the edit form; note that if you have already saved............ those changes will not be reverted."

**Comment by bpescador** [comment]
@jonkerz that works
