### ISSUE TITLE
add "NEW" to latest additions page

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#138]
Most new references are added from this page: http://antcat.org/references/latest_additions

please add the tools to add and copy references from this page.

**Comment by jonkerz** [comment]
@bpescador 
Button added in 1ed8570b4fe573e9626a379f7b9c9af8993b103f.

Re the copy feature (and ping @marekborowiec): I've no ETA for this, but it shouldn't be too hard to just manually copy the fields. And to be honest, I'm not sure I can see the benefit of this feature? Convenient, sure, but I'd have to re-implement it. I mean, there's always new tab + Ctrl-C, and you tell me, because I do not know, but how many fields do you usually copy??? I imagine the number of fields removed after copying is larger than the number kept, and if someone forgets to remove irrelevant fields, that would introduce errors in the catalog.

**Comment by bpescador** [comment]
@jonkerz  I suggest you try to create a few nested citations to see if you
would find the copy function useful.

On Mon, Apr 11, 2016 at 9:25 AM, jonkerz <notifications@github.com> wrote:

> @bpescador <https://github.com/bpescador>
> Button added in 1ed8570
> <https://github.com/calacademy-research/antcat/commit/1ed8570b4fe573e9626a379f7b9c9af8993b103f>
> .
>
> Re the copy feature (and ping @marekborowiec
> <https://github.com/marekborowiec>): I've no ETA for this, but it
> shouldn't be too hard to just manually copy the fields. And to be honest,
> I'm not sure I can see the benefit of this feature? Convenient, sure, but
> I'd have to re-implement it. I mean, there's always new tab + Ctrl-C, and
> you tell me, because I do not know, but how many fields do you usually
> copy??? I imagine the number of fields removed after copying is larger than
> the number kept, and if someone forgets to remove irrelevant fields, that
> would introduce errors in the catalog.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/calacademy-research/antcat/issues/138#issuecomment-208198606>
>



-- 
Photos from Mozambique: https://flic.kr/s/aHsku6pCu2

**Comment by jonkerz** [comment]
Implemented.
