### ISSUE TITLE
Feature request for advanced search: search only valid species name that contains your search term

### ISSUE THREAD

**Issue by marekborowiec** [calacademy-research/antcat#139]
It would be great to have a field in advanced search that allows `where species contains` in addition to searching by genus.

I was attempting to look up all valid names that contained a specific epithet of a common European ant but could not figure out a way to do this. The general search output is too cluttered with dozens of unavailable names so in this case it would have been very useful. Alternative solution would be to just allow user to filter general search results by validity.

**Comment by jonkerz** [comment]
Note: not deployed yet, links not working until then.

@marekborowiec 

There is already a checkbox for valid_only in the advanced search form, and I've added another to the "quick search" form.

About species names, I added a "where name contains" box to the advanced form. If we want to enable searching by tribe name, subspecies name, etc, we'd have to add loads of other search fields, so I think that a name field is better (and then using that in combination with the rank selector).

Examples:
* [All taxa with names containing "niger"](http://antcat.org/catalog/search?utf8=%E2%9C%93&rank=All&author_name=&year=&name=niger&genus=&biogeographic_region=&locality=&verbatim_type_locality=&type_specimen_repository=&type_specimen_code=&forms=)
* ["niger" but valid only](http://antcat.org/catalog/search?utf8=%E2%9C%93&rank=All&author_name=&year=&name=niger&genus=&biogeographic_region=&locality=&verbatim_type_locality=&type_specimen_repository=&type_specimen_code=&forms=&valid_only=true)
* ["niger", valid species only](http://antcat.org/catalog/search?utf8=%E2%9C%93&rank=Species&author_name=&year=&name=niger&genus=&biogeographic_region=&locality=&verbatim_type_locality=&type_specimen_repository=&type_specimen_code=&forms=&valid_only=true)

I've no idea why there wasn't a name field in the advanced search form before this, perhaps because searching by name was handled by the header search box. Now that the two search functions share the same page and results page, the next natural step is to merge them completely.

Note that the two searches show different results when searching by name, because the AS always searches in the name field, while the old (QS) only searches the name if the search query contains at least two words (it searches in the epithet field otherwise). That should be toggleable in the future.

**Comment by marekborowiec** [comment]
This sounds like a great solution; thanks, can't wait to try it out.

I guess the new "where name contains" field could replace "where genus contains" since when you can search by name and also further limit by rank, as you pointed out, genus name search field seems redundant.

**Comment by foozleface** [comment]
Deployed as of 9am PST

**Comment by marekborowiec** [comment]
Good stuff!
