### ISSUE TITLE
Scalable taxon-display windows

### ISSUE THREAD

**Issue by boud1** [calacademy-research/antcat#144]
It would be really nice if the taxon-display windows could be scaled, so that one does not have to scroll to see all of the names. Cross-referencing between print/pdf/excel and non-scalable AntCat windows requires repeated scrollings, especially as there are numerous columns per window given the currently set size.

**Comment by jonkerz** [comment]
@boud1 Agreed. I've had a bunch of other issues to deal with first (for example the 'copy reference feature' which I re-implemented earlier today) but this -- as in generally making the taxon browser easier to work with -- is now my top-priority.

**Comment by jonkerz** [comment]
@boud1 A quick status update as this has taken a while already. This is what I got so far, not deployed yet:
![resizable_taxon_browser_beta](https://cloud.githubusercontent.com/assets/1513381/14889142/d6da5222-0d5d-11e6-85e1-ceae1c39b7b2.png)

It is very similar to the old taxon browser, but tabbed instead of listing all ranks at the same time. Just to make that clear, it's not possible to restore the old code because the back-end code was impossible to expand on, and the front-end code/styling completely broke when I added a front-end framework (which we desperately needed to do because the styling -- and all test/back-/front-end code that depended on it -- had built up too much technical debt which made adding new features and improvements very hard).

The layout is now back to static and the splitter cannot be moved on mobiles, but I still think it's an improvement because right now on the live the site the TB covers too much of the screen and pushes down the content, and it is also frustrating to toggle it back and forth all the time.

As you can see in the screenshot, there's no footer or taxon key (yet). It was just easier to implement a prototype that way, and now that we're back to a static layout there's not a lot of space, so I'd prefer to put the partner links on the about page (also makes the coding a notch easier). As for the taxon key, always showing it makes sense even if it takes up some extra space, so I'll do that.

Another thing to consider is the titles of the rank panels, eg "Family: Formicidae" and "Subfamily: Agroecomyrmecinae", which could be changed to "Formicidae subfamilies" and "Agroecomyrmecinae tribes".

That's it for now, more to come.

**Comment by boud1** [comment]
Great! I really look forward to the changes---it will make using the
catalog much easier!

Thanks for the update!
All the best,
Brendon

On Thu, Apr 28, 2016 at 7:39 AM, jonkerz <notifications@github.com> wrote:

> @boud1 <https://github.com/boud1> A quick status update as this has taken
> a while already. This is what I got so far, not deployed yet:
> [image: resizable_taxon_browser_beta]
> <https://cloud.githubusercontent.com/assets/1513381/14889142/d6da5222-0d5d-11e6-85e1-ceae1c39b7b2.png>
>
> It is very similar to the old taxon browser, but tabbed instead of listing
> all ranks at the same time. Just to make that clear, it's not possible to
> restore the old code because the back-end code was impossible to expand on,
> and the front-end code/styling completely broke when I added a front-end
> framework (which we desperately needed to do because the styling -- and all
> test/back-/front-end code that depended on it -- had built up too much
> technical debt which made adding new features and improvements very hard).
>
> The layout is now back to static and the splitter cannot be moved on
> mobiles, but I still think it's an improvement because right now on the
> live the site the TB covers too much of the screen and pushes down the
> content, and it is also frustrating to toggle it back and forth all the
> time.
>
> As you can see in the screenshot, there's no footer or taxon key (yet). It
> was just easier to implement a prototype that way, and now that we're back
> to a static layout there's not a lot of space, so I'd prefer to put the
> partner links on the about page (also makes the coding a notch easier). As
> for the taxon key, always showing it makes sense even if it takes up some
> extra space, so I'll do that.
>
> Another thing to consider is the titles of the rank panels, eg "Family:
> Formicidae" and "Subfamily: Agroecomyrmecinae", which could be changed to
> "Formicidae subfamilies" and "Agroecomyrmecinae tribes".
>
> That's it for now, more to come.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/calacademy-research/antcat/issues/144#issuecomment-215447478>
>



-- 
Department of Entomology/Nematology
University of California, Davis
One Shields Ave.
Davis, CA 95616

**Comment by jonkerz** [comment]
@boud1 @marekborowiec

Update 2

This whole shebang will be on the test instance as soon as Joe has deployed it. It will take at least a couple of days to finish it, because I'll be unavailable during the weekend and the prototype code has to be cleaned up (and the test suite has to be updated).

Stuff:
* The panel titles were changed as mentioned above (more natural language).
* The partner links are nowhere to be found (will probably end up on the about page).
* The splitter's position is recalculated on every page request, but making the code remember if the TB was re-sized is on the roadmap, because I can image that this would be useful.
* The reason there's more space than required on pages with few child taxa (less than there are subfamilies) is because otherwise users would have to scroll or re-size the TB whenever they switched tabs (and probably stab me after getting too frustrated by it). An alternative would be to not add that spacing and automatically re-size the TB when someone clicks on a rank with more child taxa, but that makes the content jump around and someone would most definitely stab me.
* [Noticed this right now] close notification messages such as "You're logged in" before re-sizing the TB because there's a bug in the code. Will be fixed.

@foozleface Ready to be deployed, it's on this branch: https://github.com/calacademy-research/antcat/tree/2.1_taxon_browser_test_code Your don't have to look at the code in detail yet (or at all...) since all of it will be commited to the 2.1 branch is smaller chunks with proper commit messages. All tests are horribly broken, but let's try it out first.

**Comment by bpescador** [comment]
@jonkerz I took a tour of the new changes on the test site and welcome these changes.  Look forward to when 2.1 is released.
