### ISSUE TITLE
subspecies raised to species loose history

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#150]
@jonkerz @boud1
I raised to species Tetramorium atlante http://antcat.org/catalog/450143 to species the history:  Tetramorium semilaeve atlante is no longer in AntCat.  It should be automatically recorded as an obsolete combination.   

I thought we were capturing all history changes.  This is a very high priority. Without history: AntWeb will not be able to resolve names automatically.  All names in lists and for specimens in AntWeb for example can be changed automatically if historical names are kept in AntCat.

**Comment by bpescador** [comment]
@jonkerz have you looked at this issue at all?  does it seem fixable?

**Comment by jonkerz** [comment]
@bpescador I haven't had time and likely won't have too much time to do it in the near future, but this will be the first thing I'll look into. As you probably know, _most_ stuff that are deleted are actually just removed from the main database tables and moved into another table (handled by the PaperTrail software/package/gem), meaning it's possible to rebuild this type of things by puzzling together when what taxa of what rank was deleted/created/changed. Buuut that may be very hard, or at the very least time-consuming.

Not that blame is important, but did is not something I broke because I did the same thing as you on a version from before my first commit and the same thing happened. I also did the same thing on the most recent version and looked at the total number of names/taxa. In both version, there was no change in number of taxa, but both version also created a new name for the new name and kept the old in the main tables (but it's likely orphaned). I'm not sure what to do here, but automatically creating a new taxon object, setting it to a synonym and attaching the old name _could_ be a good start.

One big issue is how we handle taxt references -- and this is a much larger issue. "Insert Name" in the reference/etc sections actually means "Insert Taxon" (just noticed this, had no idea) -- looking at the source code, the Taxt model-ish helper thing has support for both names and taxa, but I added a random taxt reference by using the "Insert Name" button and it's stored in the database as a taxon reference, meaning that any references such as "Antcatia as genus of Antcatini" will change to
"Antcatia as genus of Partyantini" if the name is changed to "Partyantini" (unrelated bug: it also adds italics). I'm not even sure what we want, and how to model/code that, because some taxon references should never change while some should. And I'm actually not sure it's possible (via the GUI) to reference names opposed the taxon that currently happens to bear that name.

**Comment by foozleface** [comment]
Not quite the case; unless someone explicitly deletes a taxa - something that is only enabled for "super-admins" - or at least, that's how it should be - it always sticks around. We just change it's status accordingly. We should only ever use "delete" for a case of corrupted data (or a poorly created user entry that can't be corrected to reflect a change in literature).
