### ISSUE TITLE
subspecies need placed in same list as species

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#151]
@jonkerz @boud1
Before, subspecies were listed along with species.  This made it easy to track down subspecies name for editing.  Currently, to find a subspecies you need to click on all the species names until you find it.  This has lead editors to instead, do a search for a taxon, and the result is that they have actually edited the wrong taxa.  

Maybe the fix is just to move the subspecies back into the species box.

**Comment by jonkerz** [comment]
Probably fixed by adding an "All [child] taxa" link on genus pages (soon on the live site). I never liked that the list title said "_Polyrhachis_ species" and then included subspecies, compare:

Pre 2.0:
* "_Polyrhachis_ species" = _Polyrhachis_ species and subspecies <--- this is a lie!!
* there's no subspecies panel/section/area/list

2.0:
* "_Polyrhachis_ species" = _Polyrhachis_ species
* "_Polyrhachis sericata_ subspecies" = _Polyrhachis sericata_ subspecies
* it's not possible to list all child taxa

2.1:
* "All _Polyrhachis_ taxa" = _Polyrhachis_ species and subspecies
* "_Polyrhachis_ species" still means "_Polyrhachis_ species", and there's still a subspecies panel.

We want to have a subspecies panel because while the taxon description includes a lists of valid subspecies, it's almost impossible to find invalid subspecies without it. See for example http://antcat.org/catalog/446175 where this panel enables us to find our friends _Polyrhachis sericata pruinosa_ and _P. s. harmsi_.

**Comment by flaviaesteves** [comment]
@jonkerz Do you know when the "All taxon name taxa" will be live?

**Comment by bpescador** [comment]
@jonkerz @flaviaesteves The new All Taxa and subgenera toggles are a great addition; thank you

**Comment by jonkerz** [comment]
@flaviaesteves That was pushed with the other stuff about three weeks ago. For example, on http://antcat.org/catalog/429313 the panel says "_Polyrhachis_ species" and contains species only. If you click on "ALL TAXA" you'll get redirected to http://antcat.org/catalog/429313?display=all_taxa_in_genus and now the panel says "All _Polyrhachis_ taxa", and subgenera, species and subspecies are listed in the panel's content.
