### ISSUE TITLE
Insert Names and Refs in History

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#160]
@jonkerz  After inserting a name, or ref., please have it automatically add a ": "  after the name or ref. Currently the Ref has a space inserted afterwards and name has nothing.  Since we always need a ":" followed by a space, might as well have it automatic.

**Comment by jonkerz** [comment]
I tried to make this change when this issue was created, but it was not a quick fix because the JavaScripts are kind of hard to work with. I intend to rewrite the JS some day, and I do not expect to see a fix for this before that (unless I'm feeling particularly adventurous some late night :smile:).
