### ISSUE TITLE
Brian's wish list for Next Steps

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#181]
Bolstered by all our recent progress,  I thought I would past here my wish list for next steps in the development of AntCat.  The live link to this is here: https://www.evernote.com/shard/s604/sh/7cc4dc22-8b87-4128-baaa-ae1d753446b5/7f6ac7ee58a1aaf3d0037f107b1fb218

**References**:
* link to DOIs including zenodo doi for all older literature (Antcat will then be a tool to access dois for all literature which is needed for new publications)
* link to Plazi.org
* ~~add missing pdfs (we have them all with file name and title so it should be easy to match)~~ ##384
* ~~for a given reference, list all taxa referenced - very important when completing a review of a new paper to ensure all taxa were entered~~ #214
* ~~For a given author, link to publications~~ #215
* ~~For a given journal, link to publications from that journal~~ implemented

**new species**
* ~~pull down for type deposition institution  (we  already the list of names and acronyms of every institution)~~ #334
* ~~country pull down [need to standardize on all country names as we have done with Bioregion - we have already the standard list)~~ #216
* ~~redo type section [not useful in current form - does not provide overview of all types or help discover type status]~~ #343

**Help menus**
* ~~add help note that bioregion is not applied to fossil taxa~~ #389
* ~~add help note that includes examples format for history items~~  #486

**Taxon**
* ~~add and manage subgenus~~ #418, #153, #338
* ~~for a taxa, have link to show all references, synonyms~~ #214 (even download all references)
* refigure taxa display to highlight  synonyms
* ~for patronym and other pulldowns, add author to each taxa in pull down list (this will solve 99% of all the homonym issues which differ almost always by author)~ #50

**Search**
* ~~Change page limit (increase page limit by 10x)~~ [edit: added to catalog search results in #240]
* sorting

**Comment by jonkerz** [comment]
These are all very solid improvement, but I do have a query about increasing the number of search results. I'll not have time to work on this, but here are some comments:

> For a given journal, link to publications from that journal

Already implemented, see for example this: http://antcat.org/journals/20765

You have to go to the references' detail pages (http://antcat.org/references/132835) to see the link, because too many tests broke when I linked the journal name directly.

> refigure taxa display to highlight synonyms

We may want to go further and format all taxon links in the same way as in the taxon browser. But then black cannot be used for synonyms. And unless taxon links stand out in some other say, none of them can be green.

This is the best solution I've come up with so far:
* Underline all taxon links with a discrete-ish dashed line. We do not have to use underlines 100% consistently when it's obvious that the link leads to a taxon, for example in the taxon browser or breadcumb, because that would be ugly.
* Change the "valid" color to green.
* Change the "synonym" color to red.
* Change the "original combination" color to something that's not green.
* Keep green as the color for non-taxon links.

It's hard to tell what's the best solution without seeing it in action. Using red for valid taxa everywhere simply did not look good, and since red is generally the "error, invalid, or no-go" color, and green generally means "no problem, valid", then it makes sense to change the colors. I even tried out using blue as the general color for the whole site, so that green would only be used for valid taxa, but that also did not look good.

> Change page limit (increase page limit by 10x)

I can definitely see how it's useful, but if you have 500 of anything, then you're more listing, or looking at aggregates, rather than searching. I think there's performance for increasing both the reference and taxon search results, at least the taxon results. When do you use this? Maybe there's another way of accomplishing the same thing without making the results harder to navigate in the "normal" use case. Say a button for "Show all results".

**Comment by bpescador** [comment]
For most of my searches, I need to guess what result page to look at find
what I am looking for  -- could be page 15 or 25 - a lot of clicking around
to find the result.
I like your option to "show all results"  that would satisfy my needs and
allow me to do a search to find what I am looking for.

I also like your suggestion for the color coding of taxa; we could also
have a header: synonyms in bold for example to call them out.

**Comment by jonkerz** [comment]
Closing grab-bag issue. Feel free to add new issues for anything that's still relevant and not already done.
