### ISSUE TITLE
insert reference

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#291]
We have a large number of references to link in AntCat.  It would be easier if:

(1) As with insert name tool, insert reference allows you to select the text of the author and year that needs to be linked and after clicking insert reference it automatically adds the selected author and year into the search box.  

(2) If you click search, the search should only return a list of references that include the author in the reference author field and the year from the date of publication.  

For example, if you need to link the reference:  Bolton, 1995, a search on "Bolton, 1995: should only return those references where Bolton is an author and 1995 is in the date field.

(3) ~~After inserting a reference, please automatically add a ":" and a space after insertion.  Currently, it adds just a space.~~ see #160 

For testing, see an example where we need to link lots of references and think of a fast way to do this:  http://antcat.org/catalog/429481

**Comment by jonkerz** [comment]
> As with insert name tool, insert reference allows you to select ...

Do we currently have this functionality for names, or do you mean we should add it for names and references? Anyhow, I'm pretty sure it's not going to be a quick fix, and as mentioned in https://github.com/calacademy-research/antcat/issues/160#issuecomment-332617594, the JS is kind of hard to work with, so I don't want to change it before rewriting most of it.

**Comment by bpescador** [comment]
To insert a name, I usually type in the name in the history, then select
it, and if I then click insert name, it will automatically paste the
selection into the search box.  It is a nice feature and works really well.



On Wed, Sep 27, 2017 at 11:57 AM, Fredrik Palmkron <notifications@github.com

**Comment by jonkerz** [comment]
> it will automatically paste the selection into the search box

Funny, I had no idea there was code for this. Apparently it doesn't work in Chrome in Linux, but it works in Firefox. Implementing it for references may be a quick fix, in fact I already did the change and I'm currently running the test suite. I'll deploy it to the test instance in like 15 minutes if it works. BUT, I cannot vouch for the correctness, so it's up to you to decide if we're going to include it in the next release.

**Comment by bpescador** [comment]
it works great! I am using chrome on Mac.

I also have wondered why, after doing a search a selecting a reference, you
have to click OK again.  It seems you could just click the reference and
then have it inserted -- when a long list is returned I often forget to
scroll back up to click ok.

**Comment by jonkerz** [comment]
The reference selection thing is the test instance (aka [staging](https://en.wikipedia.org/wiki/Deployment_environment#Staging)). Test it here: http://ec2-34-213-24-19.us-west-2.compute.amazonaws.com/taxa/429481/edit

> If you click search, the search should only return a list of references that include the author in the reference author field and the year from the date of publication.

I also changed the search results to be ordered by Solr's ranking score instead of by author names, which puts the relevant results for "Bolton, 1995" *much* higher up. I did this for all results, because that makes sense.

Compare search results for "Bolton" here:
- http://ec2-34-213-24-19.us-west-2.compute.amazonaws.com/references/search?utf8=%E2%9C%93&search_type=all&q=bolton&author_q=
- http://antcat.org/references/search?utf8=%E2%9C%93&search_type=all&q=bolton&author_q=

Let's order all search results by Solr's raking, WDYT?

Also note that the reference insertion search supports keywords, so you can always filter results like this "bolton year:1995" or "author:bolton year:1995".

**Comment by bpescador** [comment]
Fredrik,

This is like wonderful - I've wanted these changes for so long and it will
be so helpful.

I agree it is a good idea to rank  all search results by Solr's raking,
