### ISSUE TITLE
valid_taxa_with_a_homonym_replaced_by_id

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#312]
This script returns the following species but they I don't see the indicated issue.  Is this script searching for a history item or is there a status that I can't see:  

![screen shot 2017-10-02 at 3 32 06 pm](https://user-images.githubusercontent.com/6276764/31102433-e8b9d994-a786-11e7-86dc-f0dde0fe8990.png)

**Comment by jonkerz** [comment]
It looks in the `homonym_replaced_by_id` column, which is stored on the taxon record. You can only see it if you change the status to "homonym". 

There are 29 taxa with a status other than "homonym", which have a `homonym_replaced_by_id`. This is wrong too, right?

![replaceby](https://user-images.githubusercontent.com/1513381/31195495-d0d7bdda-a94a-11e7-8e75-4a2bdd616d0b.png)

**Comment by bpescador** [comment]
Fredrik,  you are correct:  the 29 taxa with a status other than
"homonym", which have a homonym_replaced_by_id  need to be corrected.

can you make a script.

I will see about fixing the other ones by first switching to homonym and
then deleted the homonym_replaced_by_id.

**Comment by bpescador** [comment]
I corrected the first set of problems (still need to do the 29 taxa with a status other than
"homonym", which have a homonym_replaced_by_id ) but to prevent this from happening in the future, we need to show the replacement name field if it is filled in, even if status name = homonym is not selected.  There are fancier ways of alerting the user: highlight the box in red and indicate it needs to be deleted is one option.  Can you think of a fix for this?

**Comment by jonkerz** [comment]
I've modified the script to include all non-homonyms. Validation will be added in the future; like I mentioned in another issue, many of the current db script serve as reminders of which validations we should add.

> There are fancier ways of alerting the user: highlight the box in red and indicate it needs to be deleted is one option.

We should have this! It's actually included out of the box in Rails. The taxon form will require some refactoring before we're ready for it. This refactoring has been on the road map for a long time, so let's discuss it in Malaysia, because there will not only be changes to the behind-the-scenes code, but also how editors perform certain actions.
