### ISSUE TITLE
mark up not working in taxon history but works in Preview and for Primary type

### ISSUE THREAD

**Issue by bpescador** [calacademy-research/antcat#413]
@jonkerz 
I've been thinking about guidelines for the History section a lot lately.  I've been thinking that the current history items should have bold headers - which will help when reading through some of the very long history items.  I can't seem to find how to Bold headers like "**Status as species**" or "**Junior Synonym of**".  I tried using the markdown info here:  http://antcat.org/markdown/formatting_help and when you preview it looks fine but on the live site it does not: see this example: http://antcat.org/catalog/431953 . The last line is not bold.  If markdown will work then maybe we could have a link to the markdown help page somewhere on the page when we are editing a taxonomic history.

**Comment by jonkerz** [comment]
The markdown preview renders all tags to make it work for issues/db-scripts/etc. It should only render catalog tags when previewing history items, but since history items are being phased out, I'm fine with not fixing it.

We may want to have better support for formatting content in type information fields, but I don't want to add a dependency on markdown for them at this moment, so I will close this ticket for now.
